# 金狐（加大量血量和物理防御）（增加当前0.3的血量，0.2的防御），
# 星辰（技能强度和技能抗性）（当前0.2的技能强度，和0.2的技能抗性），
# 星辉（冷缩+魔力恢复）（减少百分之1的冷缩，0.2的魔力恢复），
# 日曜（加少量血量和物理攻击）（0.1的血量和0.2的攻击力），
# 龙魂（魔力值+少量防御）（增加0.3当前魔力值的蓝，增加0.1的防御）
# COOLDOWN
# HEALTH
# MANA
# MANA_REGEN
# MOVE_SPEED
# PHYSICAL_DAMAGE
# PHYSICAL_DEFENSE
# SKILL_DAMAGE
# SKILL_DEFENSE
picture:
  # 图片路径 和vv路径填写一样
  url: ""
  # 显示x坐标
  x: 10
  # 显示y坐标
  y: 20
  # 图片宽度
  width: 200
  # 图片高度
  height: 100
# 按钮设置
buttonSettings:
  # 通用设置
  currency:
    # url - 按钮贴图链接
    # url2 - 按钮被选中贴图链接
    url: ""
    url2: ""
  # 金狐（加大量血量和物理防御）（增加当前0.3的血量，0.2的防御），
  goldFox:
    x: 0
    y: 0
    # 图片宽度
    w: 200
    # 图片高度
    h: 100
  # 星辰（技能强度和技能抗性）（当前0.2的技能强度，和0.3的技能抗性），
  star:
    x: 0
    y: 0
    w: 200
    h: 100
  # 星辉（冷缩+魔力恢复）（减少百分之1的冷缩，0.2的魔力恢复），
  starLight:
    x: 0
    y: 0
    w: 200
    h: 100
  # 日曜（加少量血量和物理攻击）（0.1的血量和0.2的攻击力），
  sunLight:
    x: 0
    y: 0
    w: 200
    h: 100
  # 龙魂（魔力值+少量防御）（增加20+0.1当前魔力值的蓝，增加0.1的防御）
  dragonSpirit:
    x: 0
    y: 0
    w: 200
    h: 100
# 属性点显示坐标
attributePoints:
  x: 190
  y: 90